apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: mta-ui-e2e-fbc-test
  namespace: art-mta-tenant
spec:
  application: mta-8-1
  contexts:
    - description: E2E tests for MTA UI with full operator deployment (test with UI component, will move to FBC application later)
      name: component_mta-8-1-mta-ui
  params:
    # Hardcoded FBC for testing
    - name: FBC_CATALOG_IMAGE
      value: "quay.io/redhat-user-workloads/ocp-art-tenant/art-fbc:v4.20__operator_nvr__mta-operator-container-8.1.1-202604201807.p2.ga19cee4.assembly.stream.el9"

    - name: PACKAGE_NAME
      value: "mta-operator"

    - name: CHANNEL_NAME
      value: "stable-v8.1"

    - name: TEST_TIER
      value: "@ci"

    - name: OPERATOR_NAMESPACE
      value: "konveyor-tackle"

  # Reference simplified test pipeline
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/sshveta/tackle2-ui.git
      - name: revision
        value: ui_test_konflux_integration
      - name: pathInRepo
        value: .tekton/integration-tests/mta-ui-test-pipeline.yaml

  # Environment configuration
  environment:
    name: ephemeral-cluster
    type: POC # Proof of Concept cluster
    configuration:
      env:
        - name: KONVEYOR_NAMESPACE
          value: konveyor-tackle
