/**
 * Scope reference data derived from the hub's internal/auth/roles.yaml.
 *
 * The hub programmatically provisions a Keycloak realm at startup, creating
 * one client scope per resource:verb pair and mapping them to the appropriate
 * realm roles. This file mirrors that data so the UI can perform scope-based
 * permission checks without hard-coding role names anywhere.
 *
 * Source: https://github.com/konveyor/tackle2-hub/blob/main/internal/auth/roles.yaml
 */

// ---------------------------------------------------------------------------
// Per-role scope arrays
// Used by masquerade presets so dev mode accurately simulates each persona.
// ---------------------------------------------------------------------------

export const adminScopes: string[] = [
  "addons:delete",
  "addons:get",
  "addons:post",
  "addons:put",
  "adoptionplans:post",
  "analyses:delete",
  "analyses:get",
  "analyses:post",
  "analyses:put",
  "analysis.profiles:delete",
  "analysis.profiles:get",
  "analysis.profiles:post",
  "analysis.profiles:put",
  "applications:delete",
  "applications:get",
  "applications:post",
  "applications:put",
  "applications.analyses:delete",
  "applications.analyses:get",
  "applications.analyses:post",
  "applications.analyses:put",
  "applications.assessments:get",
  "applications.assessments:post",
  "applications.bucket:delete",
  "applications.bucket:get",
  "applications.bucket:post",
  "applications.bucket:put",
  "applications.facts:delete",
  "applications.facts:get",
  "applications.facts:post",
  "applications.facts:put",
  "applications.manifests:get",
  "applications.manifests:post",
  "applications.stakeholders:put",
  "applications.tags:delete",
  "applications.tags:get",
  "applications.tags:post",
  "applications.tags:put",
  "archetypes:delete",
  "archetypes:get",
  "archetypes:post",
  "archetypes:put",
  "archetypes.assessments:get",
  "archetypes.assessments:post",
  "assessments:delete",
  "assessments:get",
  "assessments:post",
  "assessments:put",
  "buckets:delete",
  "buckets:get",
  "buckets:post",
  "buckets:put",
  "businessservices:delete",
  "businessservices:get",
  "businessservices:post",
  "businessservices:put",
  "cache:delete",
  "cache:get",
  "configmaps:get",
  "dependencies:delete",
  "dependencies:get",
  "dependencies:post",
  "dependencies:put",
  "files:delete",
  "files:get",
  "files:post",
  "files:put",
  "generators:delete",
  "generators:get",
  "generators:post",
  "generators:put",
  "identities:delete",
  "identities:get",
  "identities:post",
  "identities:put",
  "imports:delete",
  "imports:get",
  "imports:post",
  "imports:put",
  "jobfunctions:delete",
  "jobfunctions:get",
  "jobfunctions:post",
  "jobfunctions:put",
  "kai:get",
  "kai:post",
  "manifests:delete",
  "manifests:get",
  "manifests:post",
  "manifests:put",
  "migrationwaves:delete",
  "migrationwaves:get",
  "migrationwaves:post",
  "migrationwaves:put",
  "platforms:delete",
  "platforms:get",
  "platforms:post",
  "platforms:put",
  "proxies:delete",
  "proxies:get",
  "proxies:post",
  "proxies:put",
  "questionnaires:delete",
  "questionnaires:get",
  "questionnaires:post",
  "questionnaires:put",
  "reviews:delete",
  "reviews:get",
  "reviews:post",
  "reviews:put",
  "rulesets:delete",
  "rulesets:get",
  "rulesets:post",
  "rulesets:put",
  "schemas:delete",
  "schemas:get",
  "schemas:post",
  "schemas:put",
  "settings:delete",
  "settings:get",
  "settings:post",
  "settings:put",
  "stakeholdergroups:delete",
  "stakeholdergroups:get",
  "stakeholdergroups:post",
  "stakeholdergroups:put",
  "stakeholders:delete",
  "stakeholders:get",
  "stakeholders:post",
  "stakeholders:put",
  "tagcategories:delete",
  "tagcategories:get",
  "tagcategories:post",
  "tagcategories:put",
  "tags:delete",
  "tags:get",
  "tags:post",
  "tags:put",
  "targets:delete",
  "targets:get",
  "targets:post",
  "targets:put",
  "tasks:delete",
  "tasks:get",
  "tasks:patch",
  "tasks:post",
  "tasks:put",
  "tasks.bucket:delete",
  "tasks.bucket:get",
  "tasks.bucket:post",
  "tasks.bucket:put",
  "tickets:delete",
  "tickets:get",
  "tickets:post",
  "tickets:put",
  "trackers:delete",
  "trackers:get",
  "trackers:post",
  "trackers:put",
];

/** tackle-architect has all admin scopes except admin-only write scopes. */
const architectAdminOnlyScopes = new Set([
  "identities:post",
  "identities:put",
  "identities:delete",
  "proxies:post",
  "proxies:put",
  "proxies:delete",
  "schemas:post",
  "schemas:put",
  "schemas:delete",
  "settings:post",
  "settings:put",
  "settings:delete",
  "trackers:post",
  "trackers:put",
  "trackers:delete",
  "questionnaires:post",
  "questionnaires:put",
  "questionnaires:delete",
  "cache:delete",
]);

export const architectScopes: string[] = adminScopes.filter(
  (s) => !architectAdminOnlyScopes.has(s)
);

export const migratorScopes: string[] = [
  "addons:get",
  "adoptionplans:post",
  "analyses:get",
  "analysis.profiles:get",
  "applications:get",
  "applications.analyses:get",
  "applications.assessments:get",
  "applications.bucket:get",
  "applications.facts:get",
  "applications.manifests:get",
  "applications.tags:get",
  "archetypes:get",
  "archetypes.assessments:get",
  "assessments:get",
  "buckets:get",
  "businessservices:get",
  "cache:get",
  "configmaps:get",
  "dependencies:delete",
  "dependencies:get",
  "dependencies:post",
  "dependencies:put",
  "files:get",
  "generators:get",
  "identities:get",
  "imports:get",
  "jobfunctions:get",
  "kai:get",
  "kai:post",
  "manifests:get",
  "migrationwaves:get",
  "platforms:get",
  "proxies:get",
  "questionnaires:get",
  "reviews:get",
  "rulesets:get",
  "schemas:get",
  "settings:get",
  "stakeholdergroups:get",
  "stakeholders:get",
  "tagcategories:get",
  "tags:get",
  "targets:get",
  "tasks:delete",
  "tasks:get",
  "tasks:patch",
  "tasks:post",
  "tasks:put",
  "tasks.bucket:delete",
  "tasks.bucket:get",
  "tasks.bucket:post",
  "tasks.bucket:put",
  "tickets:get",
  "trackers:get",
];

export const projectManagerScopes: string[] = [
  "addons:get",
  "adoptionplans:post",
  "analyses:get",
  "analysis.profiles:get",
  "applications:get",
  "applications.analyses:get",
  "applications.assessments:get",
  "applications.bucket:get",
  "applications.facts:get",
  "applications.manifests:get",
  "applications.stakeholders:put",
  "applications.tags:get",
  "archetypes:get",
  "archetypes.assessments:get",
  "assessments:get",
  "buckets:get",
  "businessservices:get",
  "cache:get",
  "configmaps:get",
  "dependencies:get",
  "files:get",
  "generators:get",
  "identities:get",
  "imports:get",
  "jobfunctions:get",
  "kai:get",
  "kai:post",
  "migrationwaves:delete",
  "migrationwaves:get",
  "migrationwaves:post",
  "migrationwaves:put",
  "platforms:get",
  "proxies:get",
  "questionnaires:get",
  "reviews:get",
  "rulesets:get",
  "settings:get",
  "stakeholdergroups:get",
  "stakeholders:get",
  "tagcategories:get",
  "tags:get",
  "targets:get",
  "tasks:get",
  "tasks.bucket:get",
  "tickets:get",
  "trackers:get",
];

// ---------------------------------------------------------------------------
// View scope sets — used by RouteWrapper and sidebar to gate navigation access.
//
// The check uses OR semantics (user needs at least one scope from the set).
// We pick write scopes unique to each tier so that having them implies the
// correct persona without requiring an exact role check.
// ---------------------------------------------------------------------------

/**
 * Any authenticated user can reach migration pages.
 * All roles (admin, architect, migrator, project-manager) have applications:get.
 */
export const migrationViewScopes: string[] = ["applications:get"];

/**
 * Only tackle-admin has write access to identities, proxies, settings, etc.
 * Presence of any of these in the token implies an admin persona.
 */
export const adminViewScopes: string[] = [
  "identities:post",
  "identities:put",
  "identities:delete",
  "proxies:post",
  "proxies:put",
  "settings:post",
  "settings:put",
  "settings:delete",
  "questionnaires:post",
  "questionnaires:put",
  "questionnaires:delete",
];
