name: Run UI tests
description: Run Konveyor UI tests using Cypress

inputs:
  test_tags:
    description: Comma separated list of test tags to run
    default: "@ci,@tier0"

  tests_ref:
    description: Ref in this repo to use for the tests
    default: main

  base_url:
    description: The base URL for the UI to test
    required: true

  metrics_url:
    description: The metrics endpoint URL
    required: false
    default: ""

  feature_auth_required:
    description: Whether authentication is enabled (if false, excludes rbac tests)
    required: false
    default: "false"

  report_artifact_name:
    description: The name of the artifact to upload.
    default: "ui-test-reports"

  # Credentials passed from secrets or environment
  keycloak_admin_password:
    description: Keycloak admin password
    required: false
    default: ""

  git_user:
    description: Git username
    required: false
    default: ""

  git_password:
    description: Git password
    required: false
    default: ""

  svn_user:
    description: SVN username
    required: false
    default: ""

  svn_password:
    description: SVN password
    required: false
    default: ""

  jira_stage_datacenter_url:
    description: Jira Stage Datacenter URL
    required: false
    default: ""

  jira_stage_bearer_token:
    description: Jira Stage Bearer Token
    required: false
    default: ""

  jira_stage_basic_login:
    description: Jira Stage Basic Login
    required: false
    default: ""

  jira_stage_basic_password:
    description: Jira Stage Basic Password
    required: false
    default: ""

  jira_atlassian_cloud_url:
    description: Jira Atlassian Cloud URL
    required: false
    default: ""

  jira_atlassian_cloud_email:
    description: Jira Atlassian Cloud Email
    required: false
    default: ""

  jira_atlassian_cloud_token:
    description: Jira Atlassian Cloud Token
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Checkout the tests (ref: ${{ inputs.tests_ref }})"
      uses: actions/checkout@v4
      with:
        ref: "${{ inputs.tests_ref }}"
        repository: konveyor/tackle2-ui
        path: ui-tests

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: "ui-tests/package.json"
        cache: "npm"
        cache-dependency-path: "ui-tests/package-lock.json"

    - name: Install dependencies
      shell: bash
      run: |
        cd ui-tests
        npm clean-install --no-audit

    - name: Run login tests
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: "${{ inputs.base_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_INITIAL_PASSWORD: Passw0rd!
        CYPRESS_KEYCLOAK_ADMIN_PASSWORD: ${{ inputs.keycloak_admin_password }}
      with:
        install: true
        working-directory: ./ui-tests
        project: ./cypress
        spec: "**/e2e/tests/login.test.ts"
        summary-title: "Login tests"

    - name: Build test spec from test tags
      id: build-test-spec
      shell: bash
      env:
        TEST_TAGS: ${{ inputs.test_tags }}
        AUTH_REQUIRED: ${{ inputs.feature_auth_required }}
      run: |
        cd ui-tests/cypress
        SPEC=$(node scripts/findTierFiles.mjs ${TEST_TAGS})

        # Exclude rbac tests if auth is not required
        if [[ "$AUTH_REQUIRED" != "true" ]]; then
          echo "Auth is disabled - excluding rbac tests"
          # Filter out any rbac test files from the spec
          SPEC=$(echo "$SPEC" | tr ',' '\n' | { grep -v '/rbac/' || true; } | tr '\n' ',' | sed 's/,$//')
        fi

        echo "test_spec=${SPEC}" >> "$GITHUB_ENV"

    - name: "Run UI tests (${{ inputs.test_tags }})"
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_INCLUDE_TAGS: "${{ inputs.test_tags }}"
        CYPRESS_EXCLUDE_TAGS: "cf,downstream"
        # These should match what is listed in `cypress/.env.example`
        CYPRESS_BASE_URL: "${{ inputs.base_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_KEYCLOAK_ADMIN_PASSWORD: ${{ inputs.keycloak_admin_password }}
        CYPRESS_GIT_USER: ${{ inputs.git_user }}
        CYPRESS_GIT_PASSWORD: ${{ inputs.git_password }}
        CYPRESS_SVN_USER: ${{ inputs.svn_user }}
        CYPRESS_SVN_PASSWORD: ${{ inputs.svn_password }}
        CYPRESS_jira_stage_datacenter_url: ${{ inputs.jira_stage_datacenter_url }}
        CYPRESS_jira_stage_bearer_token: ${{ inputs.jira_stage_bearer_token }}
        CYPRESS_jira_stage_basic_login: ${{ inputs.jira_stage_basic_login }}
        CYPRESS_jira_stage_basic_password: ${{ inputs.jira_stage_basic_password }}
        CYPRESS_jira_atlassian_cloud_url: ${{ inputs.jira_atlassian_cloud_url }}
        CYPRESS_jira_atlassian_cloud_email: ${{ inputs.jira_atlassian_cloud_email }}
        CYPRESS_jira_atlassian_cloud_token: ${{ inputs.jira_atlassian_cloud_token }}
        CYPRESS_metricsUrl: ${{ inputs.metrics_url }}
      with:
        install: false
        working-directory: ./ui-tests
        project: ./cypress
        spec: "${{ env.test_spec }}"
        summary-title: "UI tests (${{ inputs.test_tags }})"

    - name: Generate bug summary
      if: always()
      shell: bash
      run: |
        cd ui-tests/cypress
        if [[ -f run/report/index.json ]]; then
          node scripts/bug_summary.mjs run/report/index.json
        else
          echo "No run/report/index.json found; skipping bug summary generation."
        fi

    - name: Publish Bug Summary to GitHub Job Summary
      if: always()
      shell: bash
      run: |
        cd ui-tests/cypress
        echo "## Test Bug Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [[ -f run/report/bug-summary.json ]]; then
          jq -r '
            .summary |
            "| Metric | Count |
             |--------|-------|
             | Total Tests | \(.totalTests) |
             | Passing | \(.passing) |
             | Failing | \(.failing) |
             | Known Bug Failures | \(.totalBugs) |
             | Pending | \(.pending) |
             | Skipped | \(.skipped) |"
          ' run/report/bug-summary.json | sed 's/^[[:space:]]*//' >> $GITHUB_STEP_SUMMARY
        else
          echo "_Bug summary unavailable (bug-summary.json missing)_" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload cypress report data as artifact
      uses: actions/upload-artifact@v4
      if: always() && inputs.report_artifact_name != ''
      with:
        overwrite: true
        name: ${{ inputs.report_artifact_name }}
        path: |
          ./ui-tests/cypress/run
