name: Run UI tests
description: Run Konveyor UI tests using Cypress

inputs:
  test_tags:
    description: Comma separated list of test tags to run
    default: "@ci,@tier0"

  test_spec:
    description: Comma separated list of test file paths to run (overrides test_tags)
    default: ""

  tests_ref:
    description: Ref in this repo to use for the tests
    default: main

  base_url:
    description: The base URL for the UI to test
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout the tests (ref: ${{ inputs.tests_ref }})"
      uses: actions/checkout@v4
      with:
        ref: "${{ inputs.tests_ref }}"
        repository: konveyor/tackle2-ui
        path: ui-tests

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: "ui-tests/package.json"
        cache: "npm"
        cache-dependency-path: "ui-tests/package-lock.json"

    - name: Install dependencies
      shell: bash
      run: |
        cd ui-tests
        npm clean-install --no-audit

    - name: Run login tests
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: "${{ inputs.base_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_INITIAL_PASSWORD: Passw0rd!
        CYPRESS_KEYCLOAK_ADMIN_PASSWORD: admin123
      with:
        install: true
        working-directory: ./ui-tests
        project: ./cypress
        spec: "**/e2e/tests/login.test.ts"
        summary-title: "Login tests"

    - name: Build test spec from test tags or use provided spec
      id: build-test-spec
      shell: bash
      env:
        TEST_TAGS: ${{ inputs.test_tags }}
        TEST_SPEC: ${{ inputs.test_spec }}
      run: |
        cd ui-tests/cypress
        if [ -n "$TEST_SPEC" ]; then
          echo "test_spec=${TEST_SPEC}" >> "$GITHUB_ENV"
          echo "selection_mode=custom-paths" >> "$GITHUB_ENV"
        else
          SPEC=$(node scripts/findTierFiles.mjs ${TEST_TAGS})
          echo "test_spec=${SPEC}" >> "$GITHUB_ENV"
          echo "selection_mode=tags" >> "$GITHUB_ENV"
        fi

    - name: "Run UI tests (${{ env.selection_mode == 'custom-paths' && 'custom paths' || inputs.test_tags }})"
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_INCLUDE_TAGS: "${{ inputs.test_tags }}"
        # These should match what is listed in `cypress/.env.example`
        CYPRESS_BASE_URL: "${{ inputs.base_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_KEYCLOAK_ADMIN_PASSWORD: admin123
        CYPRESS_GIT_USER: gituser
        CYPRESS_GIT_PASSWORD: gitpass123
        CYPRESS_SVN_USER: svnuser
        CYPRESS_SVN_PASSWORD: svnpass123
      with:
        install: false
        working-directory: ./ui-tests
        project: ./cypress
        spec: "${{ env.test_spec }}"
        summary-title: "UI tests (${{ env.selection_mode == 'custom-paths' && 'custom paths' || inputs.test_tags }})"

    - name: Sanitize ref name for artifact
      id: sanitize
      shell: bash
      run: |
        sanitized="${{ inputs.tests_ref }}"
        sanitized="${sanitized//\//_}"
        sanitized="${sanitized//:/_}"
        sanitized="${sanitized//\\/_}"
        echo "ref=$sanitized" >> $GITHUB_OUTPUT

    - name: Upload cypress report data as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ steps.sanitize.outputs.ref }}
        path: |
          ./ui-tests/cypress/run
