name: Run UI tests
description: Run Konveyor UI tests using Cypress

inputs:
  test_tags:
    description: Comma separated list of test tags to run
    default: "@ci,@tier0"

  tests_ref:
    description: Ref in this repo to use for the tests
    default: main

  base_url:
    description: The base URL for the UI to test
    required: true

  report_artifact_name:
    description: The name of the artifact to upload.
    default: "ui-test-reports"

runs:
  using: "composite"
  steps:
    - name: "Checkout the tests (ref: ${{ inputs.tests_ref }})"
      uses: actions/checkout@v4
      with:
        ref: "${{ inputs.tests_ref }}"
        repository: konveyor/tackle2-ui
        path: ui-tests

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: "ui-tests/package.json"
        cache: "npm"
        cache-dependency-path: "ui-tests/package-lock.json"

    - name: Install dependencies
      shell: bash
      run: |
        cd ui-tests
        npm clean-install --no-audit

    - name: Run login tests
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: "${{ inputs.base_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_INITIAL_PASSWORD: Passw0rd!
        CYPRESS_KEYCLOAK_ADMIN_PASSWORD: admin123
      with:
        install: true
        working-directory: ./ui-tests
        project: ./cypress
        spec: "**/e2e/tests/login.test.ts"
        summary-title: "Login tests"

    - name: Build test spec from test tags
      id: build-test-spec
      shell: bash
      env:
        TEST_TAGS: ${{ inputs.test_tags }}
      run: |
        cd ui-tests/cypress
        SPEC=$(node scripts/findTierFiles.mjs ${TEST_TAGS})
        echo "test_spec=${SPEC}" >> "$GITHUB_ENV"

    - name: "Run UI tests (${{ inputs.test_tags }})"
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_INCLUDE_TAGS: "${{ inputs.test_tags }}"
        CYPRESS_EXCLUDE_TAGS: "cf"
        # These should match what is listed in `cypress/.env.example`
        CYPRESS_BASE_URL: "${{ inputs.base_url }}"
        CYPRESS_USER: admin
        CYPRESS_PASSWORD: Dog8code
        CYPRESS_KEYCLOAK_ADMIN_PASSWORD: admin123
        CYPRESS_GIT_USER: gituser
        CYPRESS_GIT_PASSWORD: gitpass123
        CYPRESS_SVN_USER: svnuser
        CYPRESS_SVN_PASSWORD: svnpass123
      with:
        install: false
        working-directory: ./ui-tests
        project: ./cypress
        spec: "${{ env.test_spec }}"
        summary-title: "UI tests (${{ inputs.test_tags }})"

    - name: Generate bug summary
      if: always()
      shell: bash
      run: |
        cd ui-tests/cypress
        if [[ -f run/report/index.json ]]; then
          node scripts/bug_summary.mjs run/report/index.json
        else
          echo "No run/report/index.json found; skipping bug summary generation."
        fi

    - name: Publish Bug Summary to GitHub Job Summary
      if: always()
      shell: bash
      run: |
        cd ui-tests/cypress
        echo "## Test Bug Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [[ -f run/report/bug-summary.json ]]; then
          jq -r '
            .summary |
            "| Metric | Count |
             |--------|-------|
             | Total Tests | \(.totalTests) |
             | Passing | \(.passing) |
             | Failing | \(.failing) |
             | Known Bug Failures | \(.totalBugs) |
             | Pending | \(.pending) |
             | Skipped | \(.skipped) |"
          ' run/report/bug-summary.json | sed 's/^[[:space:]]*//' >> $GITHUB_STEP_SUMMARY
        else
          echo "_Bug summary unavailable (bug-summary.json missing)_" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload cypress report data as artifact
      uses: actions/upload-artifact@v4
      if: always() && inputs.report_artifact_name != ''
      with:
        overwrite: true
        name: ${{ inputs.report_artifact_name }}
        path: |
          ./ui-tests/cypress/run
