name: Multiple Architecture Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "v*"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-build:
    uses: konveyor/release-tools/.github/workflows/build-push-images.yaml@main
    with:
      registry: ${{ vars.IMAGE_BUILD_REGISTRY || 'quay.io/konveyor' }}
      image_name: ${{ vars.IMAGE_BUILD_IMAGE_NAME || 'tackle2-ui' }}
      containerfile: "./Dockerfile"

      # keep the architectures in sync with `ci-image-build.yml`
      architectures: '[ "amd64", "arm64" ]'

      # 2023-03-19: currently needed for npm@10
      extra-args: "--ulimit nofile=4096:4096"

    secrets:
      registry_username: ${{ secrets.QUAY_PUBLISH_ROBOT }}
      registry_password: ${{ secrets.QUAY_PUBLISH_TOKEN }}
