name: Nightly CI (repo level @main)

on:
  schedule:
    - cron: "35 5 * * *" # every day @ 5:35am UTC

  workflow_dispatch:

permissions:
  contents: read

jobs:
  nightly:
    uses: ./.github/workflows/ci-repo.yml
