name: PR Checks

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
  merge_group:

jobs:
  verify:
    if: github.event_name != 'merge_group'
    runs-on: ubuntu-latest
    name: Verify PR contents
    steps:
      - name: Check Title
        id: verifier
        uses: konveyor/release-tools/cmd/verify-pr@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
